### ISSUE TITLE
Channels should not be listed in channels index before images are available

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/system-image#14]
This surfaced in the installer (https://github.com/ubports/ubports-installer/issues/1340) between the opening of `16.04/arm64/hybris/stable` and the release of the first images there. If they are listed before, it requires querying clients to do recursive lookups to check which channels actually have images for this device, which is not great. I implemented a workaround (https://github.com/ubports/system-image-node-module/pull/23), but it'd be better to fix it upstream.

**Comment by peat-psuwit** [comment]
Migrated to GitLab.

https://gitlab.com/ubports/core/system-image/-/issues/14
